### ISSUE TITLE
error on import

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#166]
Could you translate what this means?

`

468 469 470 471 472 473 | end          $new_sub_reset = last_mobile_reset.sub_resets.create(           :reset_type   => reset_record["reset_type"],           :val_1        => reset_record["val_1"].to_i,           :val_2        => $obj_vnum,
-- | --

Rails.root: /app

Application Trace | Framework Trace | Full Trace
app/controllers/areas_controller.rb:470:in `block in import_area'
app/controllers/areas_controller.rb:395:in `each_value'
app/controllers/areas_controller.rb:395:in `import_area'
app/controllers/areas_controller.rb:95:in `import'
Request
Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"+NGhq4xtBV401PkLawbTSkSrHHilctyFNMNgaEqI3u4=",
 "file"=>#<ActionDispatch::Http::UploadedFile:0x00559cb3c75e48 @tempfile=#<Tempfile:/tmp/RackMultipart20180212-4-qmi0bh>,
 @original_filename="HOM II.are",
 @content_type="application/octet-stream",
 @headers="Content-Disposition: form-data; name=\"file\"; filename=\"HOM II.are\"\r\nContent-Type: application/octet-stream\r\n">,
 "commit"=>"Import"}
`

**Comment by tyn-** [comment]
It's broken. 😉
